name: "Build using pyinstaller"

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Install pip modules
        run: pip install -r requirements.txt

      - name: Build exe
        run: pyinstaller main.py --noconsole --onefile --add-data icon.ico`;. -i icon.ico --hidden-import plyer.platforms.win.notification

      - name: Rename exe
        run: ren dist/main.exe dist/XIVLauncher-Automatic-OTP.exe

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist/XIVLauncher-Automatic-OTP.exe
            README.md